name: Checkmarx SAST Scan

on:
  push:
    branches:
      - master

jobs:
  sast-scan:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Checkmarx SAST Scan
        shell: cmd
        run: |
          echo Starting Checkmarx scan...
          call "C:\CxConsolePlugin-1.1.38\runCxConsole.cmd" Scan -v ^
            -cxserver "%CX_SERVER_URL%" ^
            -projectname "CxServer\Training\k8-cicd-pipeline" ^
            -cxuser "%CX_USER%" ^
            -cxpassword "%CX_PASSWORD%" ^
            -locationtype folder ^
            -locationpath "%CD%" ^
            -preset "Checkmarx Default" ^
            -incremental ^
            -reportpdf "CxScanReport.pdf"
