name: Checkmarx SAST Scan

on:
  push:
    branches:
      - master

jobs:
  sast-scan:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Checkmarx Scan (Debug)
        shell: pwsh
        env:
          CX_USER: adityawadekar
          CX_PASSWORD: "Demo?@@?123"
        run: |
          Write-Host "Starting Checkmarx scan in debug mode..."
          "C:\CxConsolePlugin-1.1.38\runCxConsole" Scan -v `
            -CxServer http://adityaw-lt/ `
            -ProjectName "YourProjectName" `
            -CxUser $env:CX_USER `
            -CxPassword $env:CX_PASSWORD `
            -LocationType folder `
            -LocationPath "${{ github.workspace }}" `
            -Preset "Checkmarx Default"
