name: Checkmarx SAST Scan

on:
  push:
    branches:
      - main

jobs:
  sast-scan:
    runs-on: self-hosted  # Your self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Checkmarx Scan
        run: |
          "C:\CxConsolePlugin-1.1.38\runCxConsole" Scan -v \
          -CxServer http://adityaw-lt/ \
          -ProjectName "YourProjectName" \
          -CxUser adityawadekar \
          -CxPassword "Demo?@@?123" \
          -LocationType folder \
          -LocationPath "${{ github.workspace }}" \
          -Preset "Checkmarx Default"
