name: Checkmarx SAST Scan

on:
  push:
    branches:
      - master

jobs:
  sast-scan:
    runs-on: self-hosted  # Make sure your runner is tagged as self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Checkmarx SAST Scan
        shell: cmd
        run: |
          "C:\CxConsolePlugin-1.1.38\runCxConsole.exe" Scan -v ^
          -CxServer http://adityaw-lt/ ^
          -ProjectName "k8-cicd-pipeline" ^
          -CxUser adityawadekar ^
          -CxPassword "Demo?@@?123" ^
          -LocationType folder ^
          -LocationPath "%CD%" ^
          -Preset "Checkmarx Default"
