name: Checkmarx SAST Scan

on:
  push:
    branches:
      - master

jobs:
  sast-scan:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Checkmarx Scan
        shell: cmd
        run: |
          echo Running Checkmarx SAST scan...
          call C:\CxConsolePlugin-1.1.38\runCxConsole.cmd Scan -v ^
            -CxServer "%CX_SERVER_URL%" ^
            -ProjectName "CxServer\Training\k8-cicd-pipeline" ^
            -CxUser "%CX_USER%" ^
            -CxPassword "%CX_PASSWORD%" ^
            -LocationType folder ^
            -LocationPath "%CD%" ^
            -Preset "Checkmarx Default"
