name: Checkmarx SAST Scan

on:
  push:
    branches:
      - master

jobs:
  sast-scan:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Checkmarx Scan via CxConsole
        shell: cmd
        run: |
          C:\CxConsolePlugin-1.1.38\runCxConsole.cmd Scan ^
          -CxServer http://adityaw-lt ^
          -CxUser %CX_USER% ^
          -CxPassword %CX_PASSWORD% ^
          -ProjectName "k8-cicd-pipeline" ^
          -LocationType folder ^
          -LocationPath "%GITHUB_WORKSPACE%" ^
          -Preset "Checkmarx Default" ^
          -ReportPDF "%GITHUB_WORKSPACE%\scan-report.pdf"

    env:
      CX_USER: adityawadekar
      CX_PASSWORD: Demo?@@?123
