name: Checkmarx SAST On-Prem Scan

on:
  push:
    branches:
      - main

jobs:
  checkmarx-sast:
    runs-on: self-hosted  # Must be Windows self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run CxConsole Scan
        run: |
          CxConsole.exe Scan -v ^
            -CxServer "${{ secrets.CX_SERVER_URL }}" ^
            -ProjectName "GitHub-SAST-Scan" ^
            -CxUser "${{ secrets.CX_USER }}" ^
            -CxPassword "${{ secrets.CX_PASSWORD }}" ^
            -LocationType folder ^
            -LocationPath "${{ github.workspace }}" ^
            -Preset "Checkmarx Default" ^
            -Team "/CxServer/Users" ^
            -SASTHost "${{ secrets.CX_SERVER_URL }}"
